### ISSUE TITLE
Question : How to generate the js files in assets at the ng serve / ng build

### ISSUE THREAD

**Issue by Jerome2606** [lmeijdam/angular-umd-dynamic-example#2]
Hello,

I see your repo and it's very nice you shared it :)

I'm using SystemJS as well to load my plugins but I can't figure out how to generate the js files from my typescript written plugins.

Please see my stackoverflow question about this:
https://stackoverflow.com/questions/52113569/how-to-generate-assets-from-typescript-plugins-in-angular-6

I think you can help me for this point

**Comment by lmeijdam** [comment]
Hey Jerome,

For the sake of my demo/prototype I manually built the packages using the build-in ngpackagr in Angular 6, ng build 'modulea' and copied the .umd files over to the assets folder myself ;) sure you can create a build script for this to automate this, but that was not something I've put my focus on;) Hope it helps

**Comment by Jerome2606** [comment]
How do you define the modulea in angular.json ? Do you have an example  :)

**Comment by lmeijdam** [comment]
With `ng generate library modulea`

for reference; https://blog.angularindepth.com/creating-a-library-in-angular-6-87799552e7e5

**Comment by Jerome2606** [comment]
Thanks, I will take a look at that
