### ISSUE TITLE
it can't run in production mode.

### ISSUE THREAD

**Issue by jol5** [lmeijdam/angular-umd-dynamic-example#8]
![image](https://user-images.githubusercontent.com/28615922/53554329-72d32580-3b7a-11e9-99cf-53e2a992a079.png)
I haven't made any changes. just running in ng serve --prod .

**Comment by LeoLetourneur** [comment]
Can you try 

> ng serve --prod --optimization=false

With ng build --prod, I had to use --build-optimizer=false

Optimization breaks a link somewhere...

**Comment by jol5** [comment]
thanks!!! this.compiler.compileModuleAndAllComponentsAsync(  >>>this code will load all component of my dependence over the --prod  。so, it will be slow at first time .
![image](https://user-images.githubusercontent.com/28615922/53568759-b7bc8380-3b9d-11e9-8feb-5541c49e8605.png)

**Comment by lmeijdam** [comment]
you did solve it by not changing any code or?
original code; 
`
return this.compiler.compileModuleAndAllComponentsAsync(module[`${moduleInfo.moduleName}`]).then(compiled => {
`

**Comment by jol5** [comment]
> you did solve it by not changing any code or?
> original code;
> ` return this.compiler.compileModuleAndAllComponentsAsync(module[`${moduleInfo.moduleName}`]).then(compiled => { `

yes！

**Comment by lmeijdam** [comment]
any chance of sharing what you changed? ;)

**Comment by jol5** [comment]
> any chance of sharing what you changed? ;)
nothing change；

**Comment by lmeijdam** [comment]
Okay I will close this issue! 👍
